name: premier workflow

on: workflow_dispatch

jobs:
  premier-job:
    name: mon premier job
    runs-on: ubuntu-latest
    steps:
      - name: bonjour
        run: echo "hello world!"
      - name: au revoir
        run: echo "goodbye!"

  second-job:
    name: mon second job
    runs-on: ubuntu-latest
    steps:
      - name: annonce second job
        run: echo "second job!"